final: arytmetyka.mli arytmetyka.ml
	ocamlc arytmetyka.mli arytmetyka.ml -o arytmetyka
test: arytmetyka.mli arytmetyka.ml arytmetyka_testy.ml 
	ocamlc arytmetyka.mli arytmetyka.ml arytmetyka_testy.ml -o arytmtest
clean:
	rm *.cmi *.cmo
